
/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include "can_messages_tx.h"
#include <stdbool.h>

#include "u_tx_debug.h"
#include "u_queues.h"
#include "c_utils.h"
#include "fdcan.h"
#include "bitstream.h"


static void handle_bitstream_overflow(bitstream_t *bitstream_res,
					    uint32_t can_id);

uint8_t send_front_msb_accel
(float x_force,float y_force,float z_force)
{
    can_msg_t msg;
    msg.id = 0xBAB;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_force_i = (int32_t)(x_force);
                        if(x_force_i > 32767) {x_force_i = 32767;
                        } else if(x_force_i < -32768) {x_force_i = -32768;
                        }
                        data |= ((uint32_t)(x_force_i) & 0xFFFFULL) << 48;
            
                        int32_t y_force_i = (int32_t)(y_force);
                        if(y_force_i > 32767) {y_force_i = 32767;
                        } else if(y_force_i < -32768) {y_force_i = -32768;
                        }
                        data |= ((uint32_t)(y_force_i) & 0xFFFFULL) << 32;
            
                        int32_t z_force_i = (int32_t)(z_force);
                        if(z_force_i > 32767) {z_force_i = 32767;
                        } else if(z_force_i < -32768) {z_force_i = -32768;
                        }
                        data |= ((uint32_t)(z_force_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_msb_gyro
(float x_deg,float y_deg,float z_deg)
{
    can_msg_t msg;
    msg.id = 0xBAC;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_deg_i = (int32_t)(x_deg);
                        if(x_deg_i > 32767) {x_deg_i = 32767;
                        } else if(x_deg_i < -32768) {x_deg_i = -32768;
                        }
                        data |= ((uint32_t)(x_deg_i) & 0xFFFFULL) << 48;
            
                        int32_t y_deg_i = (int32_t)(y_deg);
                        if(y_deg_i > 32767) {y_deg_i = 32767;
                        } else if(y_deg_i < -32768) {y_deg_i = -32768;
                        }
                        data |= ((uint32_t)(y_deg_i) & 0xFFFFULL) << 32;
            
                        int32_t z_deg_i = (int32_t)(z_deg);
                        if(z_deg_i > 32767) {z_deg_i = 32767;
                        } else if(z_deg_i < -32768) {z_deg_i = -32768;
                        }
                        data |= ((uint32_t)(z_deg_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_msb_mag
(float x_mag,float y_mag,float z_mag)
{
    can_msg_t msg;
    msg.id = 0xBB0;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_mag_i = (int32_t)(x_mag);
                        if(x_mag_i > 32767) {x_mag_i = 32767;
                        } else if(x_mag_i < -32768) {x_mag_i = -32768;
                        }
                        data |= ((uint32_t)(x_mag_i) & 0xFFFFULL) << 48;
            
                        int32_t y_mag_i = (int32_t)(y_mag);
                        if(y_mag_i > 32767) {y_mag_i = 32767;
                        } else if(y_mag_i < -32768) {y_mag_i = -32768;
                        }
                        data |= ((uint32_t)(y_mag_i) & 0xFFFFULL) << 32;
            
                        int32_t z_mag_i = (int32_t)(z_mag);
                        if(z_mag_i > 32767) {z_mag_i = 32767;
                        } else if(z_mag_i < -32768) {z_mag_i = -32768;
                        }
                        data |= ((uint32_t)(z_mag_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_msb_orientation
(float x_fdeg,float y_fdeg,float z_fdeg)
{
    can_msg_t msg;
    msg.id = 0xBAE;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_fdeg_i = (int32_t)(x_fdeg);
                        if(x_fdeg_i > 32767) {x_fdeg_i = 32767;
                        } else if(x_fdeg_i < -32768) {x_fdeg_i = -32768;
                        }
                        data |= ((uint32_t)(x_fdeg_i) & 0xFFFFULL) << 48;
            
                        int32_t y_fdeg_i = (int32_t)(y_fdeg);
                        if(y_fdeg_i > 32767) {y_fdeg_i = 32767;
                        } else if(y_fdeg_i < -32768) {y_fdeg_i = -32768;
                        }
                        data |= ((uint32_t)(y_fdeg_i) & 0xFFFFULL) << 32;
            
                        int32_t z_fdeg_i = (int32_t)(z_fdeg);
                        if(z_fdeg_i > 32767) {z_fdeg_i = 32767;
                        } else if(z_fdeg_i < -32768) {z_fdeg_i = -32768;
                        }
                        data |= ((uint32_t)(z_fdeg_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_msb_pressure_sensor
(float pressure,float temperature)
{
    can_msg_t msg;
    msg.id = 0xBB1;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t pressure_i = (uint32_t)(pressure);
                        if(pressure_i > 4294967295ULL) {pressure_i = 4294967295;
                        }
                        data |= ((pressure_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t temperature_i = (uint32_t)(temperature);
                        if(temperature_i > 4294967295ULL) {temperature_i = 4294967295;
                        }
                        data |= ((temperature_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_temperature_sensor
(float temperature,float humidity)
{
    can_msg_t msg;
    msg.id = 0xBAF;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t temperature_i = (uint32_t)(temperature);
                        if(temperature_i > 4294967295ULL) {temperature_i = 4294967295;
                        }
                        data |= ((temperature_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t humidity_i = (uint32_t)(humidity);
                        if(humidity_i > 4294967295ULL) {humidity_i = 4294967295;
                        }
                        data |= ((humidity_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_msb_strain_one_and_two
(uint32_t strain1,uint32_t strain2)
{
    can_msg_t msg;
    msg.id = 0xDAA;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t strain1_i = (uint32_t)(strain1);
                        if(strain1_i > 4294967295ULL) {strain1_i = 4294967295;
                        }
                        data |= ((strain1_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t strain2_i = (uint32_t)(strain2);
                        if(strain2_i > 4294967295ULL) {strain2_i = 4294967295;
                        }
                        data |= ((strain2_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_msb_strain_three_and_four
(uint32_t strain3,uint32_t strain4)
{
    can_msg_t msg;
    msg.id = 0xDAB;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t strain3_i = (uint32_t)(strain3);
                        if(strain3_i > 4294967295ULL) {strain3_i = 4294967295;
                        }
                        data |= ((strain3_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t strain4_i = (uint32_t)(strain4);
                        if(strain4_i > 4294967295ULL) {strain4_i = 4294967295;
                        }
                        data |= ((strain4_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_shockpot
(uint32_t shock1,uint32_t shock2)
{
    can_msg_t msg;
    msg.id = 0xDAE;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t shock1_i = (uint32_t)(shock1);
                        if(shock1_i > 4294967295ULL) {shock1_i = 4294967295;
                        }
                        data |= ((shock1_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t shock2_i = (uint32_t)(shock2);
                        if(shock2_i > 4294967295ULL) {shock2_i = 4294967295;
                        }
                        data |= ((shock2_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_msb_load_cells
(uint32_t cell1,uint32_t cell2)
{
    can_msg_t msg;
    msg.id = 0xDAF;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t cell1_i = (uint32_t)(cell1);
                        if(cell1_i > 4294967295ULL) {cell1_i = 4294967295;
                        }
                        data |= ((cell1_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t cell2_i = (uint32_t)(cell2);
                        if(cell2_i > 4294967295ULL) {cell2_i = 4294967295;
                        }
                        data |= ((cell2_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_wheel_rpm
(uint16_t Front Right,uint16_t Front Left)
{
    can_msg_t msg;
    msg.id = 0xDB0;
    msg.id_is_extended = true;
            uint32_t data = 0;
            msg.len = 4;
                        uint32_t Front Right_i = (uint32_t)(Front Right);
                        if(Front Right_i > 65535ULL) {Front Right_i = 65535;
                        }
                        data |= ((Front Right_i) & 0xFFFFULL) << 16;
            
                        uint32_t Front Left_i = (uint32_t)(Front Left);
                        if(Front Left_i > 65535ULL) {Front Left_i = 65535;
                        }
                        data |= ((Front Left_i) & 0xFFFFULL) << 0;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_front_msb_wheel_angle
(uint32_t angle1)
{
    can_msg_t msg;
    msg.id = 0xDAD;
    msg.id_is_extended = true;
            uint32_t data = 0;
            msg.len = 4;
                        uint32_t angle1_i = (uint32_t)(angle1);
                        if(angle1_i > 4294967295ULL) {angle1_i = 4294967295;
                        }
                        data |= ((angle1_i) & 0xFFFFFFFFULL) << 0;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_accel
(float x_force,float y_force,float z_force)
{
    can_msg_t msg;
    msg.id = 0xBBF;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_force_i = (int32_t)(x_force);
                        if(x_force_i > 32767) {x_force_i = 32767;
                        } else if(x_force_i < -32768) {x_force_i = -32768;
                        }
                        data |= ((uint32_t)(x_force_i) & 0xFFFFULL) << 48;
            
                        int32_t y_force_i = (int32_t)(y_force);
                        if(y_force_i > 32767) {y_force_i = 32767;
                        } else if(y_force_i < -32768) {y_force_i = -32768;
                        }
                        data |= ((uint32_t)(y_force_i) & 0xFFFFULL) << 32;
            
                        int32_t z_force_i = (int32_t)(z_force);
                        if(z_force_i > 32767) {z_force_i = 32767;
                        } else if(z_force_i < -32768) {z_force_i = -32768;
                        }
                        data |= ((uint32_t)(z_force_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_gyro
(float x_deg,float y_deg,float z_deg)
{
    can_msg_t msg;
    msg.id = 0xBC0;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_deg_i = (int32_t)(x_deg);
                        if(x_deg_i > 32767) {x_deg_i = 32767;
                        } else if(x_deg_i < -32768) {x_deg_i = -32768;
                        }
                        data |= ((uint32_t)(x_deg_i) & 0xFFFFULL) << 48;
            
                        int32_t y_deg_i = (int32_t)(y_deg);
                        if(y_deg_i > 32767) {y_deg_i = 32767;
                        } else if(y_deg_i < -32768) {y_deg_i = -32768;
                        }
                        data |= ((uint32_t)(y_deg_i) & 0xFFFFULL) << 32;
            
                        int32_t z_deg_i = (int32_t)(z_deg);
                        if(z_deg_i > 32767) {z_deg_i = 32767;
                        } else if(z_deg_i < -32768) {z_deg_i = -32768;
                        }
                        data |= ((uint32_t)(z_deg_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_mag
(float x_mag,float y_mag,float z_mag)
{
    can_msg_t msg;
    msg.id = 0xBC4;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_mag_i = (int32_t)(x_mag);
                        if(x_mag_i > 32767) {x_mag_i = 32767;
                        } else if(x_mag_i < -32768) {x_mag_i = -32768;
                        }
                        data |= ((uint32_t)(x_mag_i) & 0xFFFFULL) << 48;
            
                        int32_t y_mag_i = (int32_t)(y_mag);
                        if(y_mag_i > 32767) {y_mag_i = 32767;
                        } else if(y_mag_i < -32768) {y_mag_i = -32768;
                        }
                        data |= ((uint32_t)(y_mag_i) & 0xFFFFULL) << 32;
            
                        int32_t z_mag_i = (int32_t)(z_mag);
                        if(z_mag_i > 32767) {z_mag_i = 32767;
                        } else if(z_mag_i < -32768) {z_mag_i = -32768;
                        }
                        data |= ((uint32_t)(z_mag_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_orientation
(float x_fdeg,float y_fdeg,float z_fdeg)
{
    can_msg_t msg;
    msg.id = 0xBC2;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        int32_t x_fdeg_i = (int32_t)(x_fdeg);
                        if(x_fdeg_i > 32767) {x_fdeg_i = 32767;
                        } else if(x_fdeg_i < -32768) {x_fdeg_i = -32768;
                        }
                        data |= ((uint32_t)(x_fdeg_i) & 0xFFFFULL) << 48;
            
                        int32_t y_fdeg_i = (int32_t)(y_fdeg);
                        if(y_fdeg_i > 32767) {y_fdeg_i = 32767;
                        } else if(y_fdeg_i < -32768) {y_fdeg_i = -32768;
                        }
                        data |= ((uint32_t)(y_fdeg_i) & 0xFFFFULL) << 32;
            
                        int32_t z_fdeg_i = (int32_t)(z_fdeg);
                        if(z_fdeg_i > 32767) {z_fdeg_i = 32767;
                        } else if(z_fdeg_i < -32768) {z_fdeg_i = -32768;
                        }
                        data |= ((uint32_t)(z_fdeg_i) & 0xFFFFULL) << 16;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_pressure_sensor
(float pressure,float temperature)
{
    can_msg_t msg;
    msg.id = 0xBC5;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t pressure_i = (uint32_t)(pressure);
                        if(pressure_i > 4294967295ULL) {pressure_i = 4294967295;
                        }
                        data |= ((pressure_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t temperature_i = (uint32_t)(temperature);
                        if(temperature_i > 4294967295ULL) {temperature_i = 4294967295;
                        }
                        data |= ((temperature_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_temperature_sensor
(float temperature,float humidity)
{
    can_msg_t msg;
    msg.id = 0xBC3;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t temperature_i = (uint32_t)(temperature);
                        if(temperature_i > 4294967295ULL) {temperature_i = 4294967295;
                        }
                        data |= ((temperature_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t humidity_i = (uint32_t)(humidity);
                        if(humidity_i > 4294967295ULL) {humidity_i = 4294967295;
                        }
                        data |= ((humidity_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_strain_one_and_two
(uint32_t strain1,uint32_t strain2)
{
    can_msg_t msg;
    msg.id = 0xDBE;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t strain1_i = (uint32_t)(strain1);
                        if(strain1_i > 4294967295ULL) {strain1_i = 4294967295;
                        }
                        data |= ((strain1_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t strain2_i = (uint32_t)(strain2);
                        if(strain2_i > 4294967295ULL) {strain2_i = 4294967295;
                        }
                        data |= ((strain2_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_strain_three_and_four
(uint32_t strain3,uint32_t strain4)
{
    can_msg_t msg;
    msg.id = 0xDBF;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t strain3_i = (uint32_t)(strain3);
                        if(strain3_i > 4294967295ULL) {strain3_i = 4294967295;
                        }
                        data |= ((strain3_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t strain4_i = (uint32_t)(strain4);
                        if(strain4_i > 4294967295ULL) {strain4_i = 4294967295;
                        }
                        data |= ((strain4_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_shockpot
(uint32_t shock1,uint32_t shock2)
{
    can_msg_t msg;
    msg.id = 0xDC2;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t shock1_i = (uint32_t)(shock1);
                        if(shock1_i > 4294967295ULL) {shock1_i = 4294967295;
                        }
                        data |= ((shock1_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t shock2_i = (uint32_t)(shock2);
                        if(shock2_i > 4294967295ULL) {shock2_i = 4294967295;
                        }
                        data |= ((shock2_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_load_cells
(uint32_t cell1,uint32_t cell2)
{
    can_msg_t msg;
    msg.id = 0xDC3;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t cell1_i = (uint32_t)(cell1);
                        if(cell1_i > 4294967295ULL) {cell1_i = 4294967295;
                        }
                        data |= ((cell1_i) & 0xFFFFFFFFULL) << 32;
            
                        uint32_t cell2_i = (uint32_t)(cell2);
                        if(cell2_i > 4294967295ULL) {cell2_i = 4294967295;
                        }
                        data |= ((cell2_i) & 0xFFFFFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_rear_wheel_rpm
(uint16_t Rear Right,uint16_t Rear Left)
{
    can_msg_t msg;
    msg.id = 0xDB1;
    msg.id_is_extended = true;
            uint32_t data = 0;
            msg.len = 4;
                        uint32_t Rear Right_i = (uint32_t)(Rear Right);
                        if(Rear Right_i > 65535ULL) {Rear Right_i = 65535;
                        }
                        data |= ((Rear Right_i) & 0xFFFFULL) << 16;
            
                        uint32_t Rear Left_i = (uint32_t)(Rear Left);
                        if(Rear Left_i > 65535ULL) {Rear Left_i = 65535;
                        }
                        data |= ((Rear Left_i) & 0xFFFFULL) << 0;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_thermocouple
(uint32_t thermo1)
{
    can_msg_t msg;
    msg.id = 0xDAC;
    msg.id_is_extended = true;
            uint32_t data = 0;
            msg.len = 4;
                        uint32_t thermo1_i = (uint32_t)(thermo1);
                        if(thermo1_i > 4294967295ULL) {thermo1_i = 4294967295;
                        }
                        data |= ((thermo1_i) & 0xFFFFFFFFULL) << 0;
            
            uint32_t data_bigendian = __builtin_bswap32(data);
            memcpy(msg.data, &data_bigendian, 4);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}

uint8_t send_back_msb_tof
(uint16_t quadrant1,uint16_t quadrant2,uint16_t quadrant3,uint16_t quadrant4)
{
    can_msg_t msg;
    msg.id = 0xBA0;
    msg.id_is_extended = true;
            uint64_t data = 0;
            msg.len = 8;
                        uint32_t quadrant1_i = (uint32_t)(quadrant1);
                        if(quadrant1_i > 65535ULL) {quadrant1_i = 65535;
                        }
                        data |= ((quadrant1_i) & 0xFFFFULL) << 48;
            
                        uint32_t quadrant2_i = (uint32_t)(quadrant2);
                        if(quadrant2_i > 65535ULL) {quadrant2_i = 65535;
                        }
                        data |= ((quadrant2_i) & 0xFFFFULL) << 32;
            
                        uint32_t quadrant3_i = (uint32_t)(quadrant3);
                        if(quadrant3_i > 65535ULL) {quadrant3_i = 65535;
                        }
                        data |= ((quadrant3_i) & 0xFFFFULL) << 16;
            
                        uint32_t quadrant4_i = (uint32_t)(quadrant4);
                        if(quadrant4_i > 65535ULL) {quadrant4_i = 65535;
                        }
                        data |= ((quadrant4_i) & 0xFFFFULL) << 0;
            
            uint64_t data_bigendian = __builtin_bswap64(data);
            memcpy(msg.data, &data_bigendian, 8);

    return queue_send(&can_outgoing, &msg, TX_NO_WAIT);
}



/// @brief A helper which sends appropriate error to stdout and CAN if a bistream overflows
/// @param bitstream_res The bitstream to check for overflow
/// @param can_id The CAN ID this bistream data is intended for
/// @return 0 if success
static void handle_bitstream_overflow(bitstream_t *bitstream_res,
					    uint32_t can_id)
{
	if (!bitstream_res->overflow) {
		return;
	}

    
}