#ifndef _CAN_MSGS_RX_H
#define _CAN_MSGS_RX_H

/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/

#include <stdbool.h>

#include "u_tx_debug.h"
#include "u_queues.h"
#include "c_utils.h"
#include "fdcan.h"
#include "bitstream.h"

typedef struct {
 uint8_t state;
 float temp_average;
} bms_status_t;

void receive_bms_status(const can_msg_t *message, bms_status_t *bms_status);

typedef struct {
 float high_val;
 uint8_t high_chip;
 uint8_t high_cell;
 float low_val;
 uint8_t low_chip;
 uint8_t low_cell;
 float avg_val;
} cell_voltage_t;

void receive_cell_voltage(const can_msg_t *message, cell_voltage_t *cell_voltage);

typedef struct {
 float high_val;
 uint8_t high_chip;
 uint8_t high_cell;
 float low_val;
 uint8_t low_chip;
 uint8_t low_cell;
 float avg_val;
} cell_temperatures_t;

void receive_cell_temperatures(const can_msg_t *message, cell_temperatures_t *cell_temperatures);

typedef struct {
 float seg1;
 float seg2;
 float seg3;
 float seg4;
 float seg5;
} segment_temperatures_t;

void receive_segment_temperatures(const can_msg_t *message, segment_temperatures_t *segment_temperatures);

typedef struct {
 uint8_t state;
 uint8_t break_location;
 uint8_t verification_attempts;
 uint8_t recovery_successful;
} segment_isospi_communication_status_t;

void receive_segment_isospi_communication_status(const can_msg_t *message, segment_isospi_communication_status_t *segment_isospi_communication_status);

typedef struct {
 bool dcl_enforce;
 bool ccl_enforce;
 bool low_cell_volt;
 bool high_cell_volt;
 bool high_charge_volt;
 bool pack_hot;
 bool die_temp_max;
 bool segment_comms;
 bool hv_plate_comms;
} fault_status_t;

void receive_fault_status(const can_msg_t *message, fault_status_t *fault_status);

typedef struct {
 float seg1;
 float seg2;
 float seg3;
 float seg4;
 float seg5;
} segment_average_voltages_t;

void receive_segment_average_voltages(const can_msg_t *message, segment_average_voltages_t *segment_average_voltages);

typedef struct {
 float seg1;
 float seg2;
 float seg3;
 float seg4;
 float seg5;
} segment_total_voltages_t;

void receive_segment_total_voltages(const can_msg_t *message, segment_total_voltages_t *segment_total_voltages);

typedef struct {
 float seg1;
 float seg2;
 float seg3;
 float seg4;
 float seg5;
} segment_delta_voltages_t;

void receive_segment_delta_voltages(const can_msg_t *message, segment_delta_voltages_t *segment_delta_voltages);

typedef struct {
 uint8_t spare0;
 uint8_t spare1;
 uint16_t spare2;
 uint32_t spare3;
} bms_debug_t;

void receive_bms_debug(const can_msg_t *message, bms_debug_t *bms_debug);

typedef struct {
 uint8_t start_stop;
 uint8_t code;
 float value;
} bms_fault_timers_t;

void receive_bms_fault_timers(const can_msg_t *message, bms_fault_timers_t *bms_fault_timers);

typedef struct {
 uint8_t major;
 uint8_t minor;
 uint8_t patch;
 bool dirty;
 bool local_commit;
} shepherd_version_tag_t;

void receive_shepherd_version_tag(const can_msg_t *message, shepherd_version_tag_t *shepherd_version_tag);

typedef struct {
 uint32_t short_hash;
 uint32_t author_hash;
} shepherd_version_hash_t;

void receive_shepherd_version_hash(const can_msg_t *message, shepherd_version_hash_t *shepherd_version_hash);

typedef struct {
 uint32_t overflow_can_id;
 uint16_t overflow_cnt;
} overflow_notification_for_percell_t;

void receive_overflow_notification_for_percell(const can_msg_t *message, overflow_notification_for_percell_t *overflow_notification_for_percell);

typedef struct {
 float therm;
 float voltage_a;
 float voltage_b;
 uint8_t chip_id;
 uint8_t cell_a;
 uint8_t cell_b;
 bool discharging_a;
 bool discharging_b;
 bool cvs_a;
 bool cvs_b;
} alpha_cell_data_debug_t;

void receive_alpha_cell_data_debug(const can_msg_t *message, alpha_cell_data_debug_t *alpha_cell_data_debug);

typedef struct {
 float therm;
 float voltage_a;
 float voltage_b;
 uint8_t chip_id;
 uint8_t cell_a;
 uint8_t cell_b;
 bool discharging_a;
 bool discharging_b;
 bool cvs_a;
 bool cvs_b;
} beta_cell_data_debug_t;

void receive_beta_cell_data_debug(const can_msg_t *message, beta_cell_data_debug_t *beta_cell_data_debug);

typedef struct {
 uint8_t chip_id;
 float die_temp;
 float vpv;
 float vmv;
 bool va_ov;
 bool va_uv;
 bool vd_ov;
 bool vd_uv;
 bool vde;
 bool vdel;
 bool spiflt;
 bool sleep;
 bool thsd;
 bool tmodchk;
 bool oscchk;
} alpha_chip_a_debug_t;

void receive_alpha_chip_a_debug(const can_msg_t *message, alpha_chip_a_debug_t *alpha_chip_a_debug);

typedef struct {
 float vres;
 uint8_t chip_id;
 float vref2;
 float v_analog;
 float v_digital;
 bool otp1_med;
 bool opt2_med;
} alpha_chip_b_debug_t;

void receive_alpha_chip_b_debug(const can_msg_t *message, alpha_chip_b_debug_t *alpha_chip_b_debug);

typedef struct {
 uint8_t chip_id;
 float die_temp;
 float vpv;
 float vmv;
 bool va_ov;
 bool va_uv;
 bool vd_ov;
 bool vd_uv;
 bool vde;
 bool vdel;
 bool spiflt;
 bool sleep;
 bool thsd;
 bool tmodchk;
 bool oscchk;
} beta_chip_a_debug_t;

void receive_beta_chip_a_debug(const can_msg_t *message, beta_chip_a_debug_t *beta_chip_a_debug);

typedef struct {
 float vres;
 uint8_t chip_id;
 float vref2;
 float v_analog;
 float v_digital;
 bool otp1_med;
 bool opt2_med;
} beta_chip_b_debug_t;

void receive_beta_chip_b_debug(const can_msg_t *message, beta_chip_b_debug_t *beta_chip_b_debug);

typedef struct {
 uint8_t fan_duty_cycle;
} fan_duty_cycle_percentage_t;

void receive_fan_duty_cycle_percentage(const can_msg_t *message, fan_duty_cycle_percentage_t *fan_duty_cycle_percentage);

typedef struct {
 uint8_t chip_id;
 float therm_temp_1;
 float therm_temp_2;
 float therm_temp_3;
} onboard_therm_temperatures_t;

void receive_onboard_therm_temperatures(const can_msg_t *message, onboard_therm_temperatures_t *onboard_therm_temperatures);

typedef struct {
 bool precharge_status;
} precharge_status_t;

void receive_precharge_status(const can_msg_t *message, precharge_status_t *precharge_status);

typedef struct {
 float batt_voltage;
 float ts_voltage;
 float shunt_temp;
 float pack_current;
} hv_plate_data_t;

void receive_hv_plate_data(const can_msg_t *message, hv_plate_data_t *hv_plate_data);

typedef struct {
 uint8_t chip_id;
 uint16_t pec_errors;
} segment_pec_errors_t;

void receive_segment_pec_errors(const can_msg_t *message, segment_pec_errors_t *segment_pec_errors);

typedef struct {
 uint16_t pec_errors;
} hv_plate_pec_errors_t;

void receive_hv_plate_pec_errors(const can_msg_t *message, hv_plate_pec_errors_t *hv_plate_pec_errors);

typedef struct {
 uint16_t flags;
 float vreg;
 float tmp1;
 float vref1p25;
 uint16_t osccnt;
} hv_plate_diagnostics_t;

void receive_hv_plate_diagnostics(const can_msg_t *message, hv_plate_diagnostics_t *hv_plate_diagnostics);

typedef struct {
 float epad;
 float vdig;
 float vdd;
 float tmp2;
 float vdiv;
} hv_plate_diagnostics_second_t;

void receive_hv_plate_diagnostics_second(const can_msg_t *message, hv_plate_diagnostics_second_t *hv_plate_diagnostics_second);

typedef struct {
 float internal_temp;
} bms_onboard_temperature_t;

void receive_bms_onboard_temperature(const can_msg_t *message, bms_onboard_temperature_t *bms_onboard_temperature);

typedef struct {
 float imu_accelerometer_x;
 float imu_accelerometer_y;
 float imu_accelerometer_z;
} bms_imu_accelerometer_t;

void receive_bms_imu_accelerometer(const can_msg_t *message, bms_imu_accelerometer_t *bms_imu_accelerometer);

typedef struct {
 float imu_gyro_x;
 float imu_gyro_y;
 float imu_gyro_z;
} bms_imu_gyro_t;

void receive_bms_imu_gyro(const can_msg_t *message, bms_imu_gyro_t *bms_imu_gyro);

typedef struct {
 float Pack_SoC;
 float Pack_SoC_Drift;
} pack_soc_status_t;

void receive_pack_soc_status(const can_msg_t *message, pack_soc_status_t *pack_soc_status);

typedef struct {
 bool shutdown;
} shutdown_as_read_by_bms_t;

void receive_shutdown_as_read_by_bms(const can_msg_t *message, shutdown_as_read_by_bms_t *shutdown_as_read_by_bms);

typedef struct {
 float accel_x;
 float accel_y;
 float accel_z;
} lightning_board_imu_acceleration_data_t;

void receive_lightning_board_imu_acceleration_data(const can_msg_t *message, lightning_board_imu_acceleration_data_t *lightning_board_imu_acceleration_data);

typedef struct {
 float gyro_x;
 float gyro_y;
 float gyro_z;
} lightning_board_imu_gyro_data_t;

void receive_lightning_board_imu_gyro_data(const can_msg_t *message, lightning_board_imu_gyro_data_t *lightning_board_imu_gyro_data);

typedef struct {
 uint8_t interrupt;
 uint8_t distance;
 uint32_t energy;
} lightning_board_lightning_sensor_information_t;

void receive_lightning_board_lightning_sensor_information(const can_msg_t *message, lightning_board_lightning_sensor_information_t *lightning_board_lightning_sensor_information);

typedef struct {
 float mag_x;
 float mag_y;
 float mag_z;
} lightning_board_magnometer_sensor_information_t;

void receive_lightning_board_magnometer_sensor_information(const can_msg_t *message, lightning_board_magnometer_sensor_information_t *lightning_board_magnometer_sensor_information);

typedef struct {
 uint8_t state;
} dashboard_efuse_state_t;

void receive_dashboard_efuse_state(const can_msg_t *message, dashboard_efuse_state_t *dashboard_efuse_state);

typedef struct {
 uint8_t state;
} brake_efuse_state_t;

void receive_brake_efuse_state(const can_msg_t *message, brake_efuse_state_t *brake_efuse_state);

typedef struct {
 uint8_t state;
} shutdown_efuse_state_t;

void receive_shutdown_efuse_state(const can_msg_t *message, shutdown_efuse_state_t *shutdown_efuse_state);

typedef struct {
 uint8_t state;
} lv_efuse_state_t;

void receive_lv_efuse_state(const can_msg_t *message, lv_efuse_state_t *lv_efuse_state);

typedef struct {
 uint8_t state;
} radfan_efuse_state_t;

void receive_radfan_efuse_state(const can_msg_t *message, radfan_efuse_state_t *radfan_efuse_state);

typedef struct {
 uint8_t state;
} fanbatt_efuse_state_t;

void receive_fanbatt_efuse_state(const can_msg_t *message, fanbatt_efuse_state_t *fanbatt_efuse_state);

typedef struct {
 uint8_t state;
} pumpone_efuse_state_t;

void receive_pumpone_efuse_state(const can_msg_t *message, pumpone_efuse_state_t *pumpone_efuse_state);

typedef struct {
 uint8_t state;
} pumptwo_efuse_state_t;

void receive_pumptwo_efuse_state(const can_msg_t *message, pumptwo_efuse_state_t *pumptwo_efuse_state);

typedef struct {
 uint8_t state;
} battbox_efuse_state_t;

void receive_battbox_efuse_state(const can_msg_t *message, battbox_efuse_state_t *battbox_efuse_state);

typedef struct {
 uint8_t state;
} mc_efuse_state_t;

void receive_mc_efuse_state(const can_msg_t *message, mc_efuse_state_t *mc_efuse_state);

typedef struct {
 uint8_t state;
} spare_efuse_state_t;

void receive_spare_efuse_state(const can_msg_t *message, spare_efuse_state_t *spare_efuse_state);

typedef struct {
 uint8_t command;
} rtds_command_message_t;

void receive_rtds_command_message(const can_msg_t *message, rtds_command_message_t *rtds_command_message);

typedef struct {
 uint8_t button_id;
} wheel_buttons_t;

void receive_wheel_buttons(const can_msg_t *message, wheel_buttons_t *wheel_buttons);

typedef struct {
 float current_target_ac;
} ac_current_command_t;

void receive_ac_current_command(const can_msg_t *message, ac_current_command_t *ac_current_command);

typedef struct {
 float brake_ac_current;
} brake_current_command_t;

void receive_brake_current_command(const can_msg_t *message, brake_current_command_t *brake_current_command);

typedef struct {
 float max_current_ac_target;
} max_ac_current_command_t;

void receive_max_ac_current_command(const can_msg_t *message, max_ac_current_command_t *max_ac_current_command);

typedef struct {
 float max_ac_brake_current_target;
} max_ac_brake_current_command_t;

void receive_max_ac_brake_current_command(const can_msg_t *message, max_ac_brake_current_command_t *max_ac_brake_current_command);

typedef struct {
 float max_dc_current_target;
} max_dc_current_command_t;

void receive_max_dc_current_command(const can_msg_t *message, max_dc_current_command_t *max_dc_current_command);

typedef struct {
 float max_dc_brake_current_target;
} max_dc_brake_current_command_t;

void receive_max_dc_brake_current_command(const can_msg_t *message, max_dc_brake_current_command_t *max_dc_brake_current_command);

typedef struct {
 uint8_t drive_enable;
} drive_enable_command_t;

void receive_drive_enable_command(const can_msg_t *message, drive_enable_command_t *drive_enable_command);

typedef struct {
 float charge_volts;
 float charge_current;
 uint8_t enable_charging;
} bms_charge_message_send_t;

void receive_bms_charge_message_send(const can_msg_t *message, bms_charge_message_send_t *bms_charge_message_send);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} dashboard_efuse_t;

void receive_dashboard_efuse(const can_msg_t *message, dashboard_efuse_t *dashboard_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} brake_efuse_t;

void receive_brake_efuse(const can_msg_t *message, brake_efuse_t *brake_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} shutdown_efuse_t;

void receive_shutdown_efuse(const can_msg_t *message, shutdown_efuse_t *shutdown_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} lv_efuse_t;

void receive_lv_efuse(const can_msg_t *message, lv_efuse_t *lv_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} radfan_efuse_t;

void receive_radfan_efuse(const can_msg_t *message, radfan_efuse_t *radfan_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} fanbatt_efuse_t;

void receive_fanbatt_efuse(const can_msg_t *message, fanbatt_efuse_t *fanbatt_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} pumpone_efuse_t;

void receive_pumpone_efuse(const can_msg_t *message, pumpone_efuse_t *pumpone_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} pumptwo_efuse_t;

void receive_pumptwo_efuse(const can_msg_t *message, pumptwo_efuse_t *pumptwo_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} battbox_efuse_t;

void receive_battbox_efuse(const can_msg_t *message, battbox_efuse_t *battbox_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} mc_efuse_t;

void receive_mc_efuse(const can_msg_t *message, mc_efuse_t *mc_efuse);

typedef struct {
 uint16_t ADC;
 float voltage;
 float current;
 bool is_faulted;
 bool is_enabled;
 uint8_t control_state;
} spare_efuse_t;

void receive_spare_efuse(const can_msg_t *message, spare_efuse_t *spare_efuse);

typedef struct {
 bool bms_gpio;
 bool bots_gpio;
 bool spare_gpio;
 bool bspd_gpio;
 bool hv_c;
 bool hvd_gpio;
 bool imd_gpio;
 bool ckpt_gpio;
 bool inertia_sw_gpio;
 bool tsms_gpio;
 uint8_t UNUSED;
} shutdown_pins_t;

void receive_shutdown_pins(const can_msg_t *message, shutdown_pins_t *shutdown_pins);

typedef struct {
 bool home_mode;
 uint8_t nero_index;
 int32_t car_speed;
 bool tsms;
 uint32_t torque_limit_percentage;
 bool reverse;
 uint16_t regen_limit;
 bool launch_control;
 uint8_t functional_state;
 bool traction_control;
} car_state_t;

void receive_car_state(const can_msg_t *message, car_state_t *car_state);

typedef struct {
 float accel_norm;
 float brake_norm;
} pedal_percent_pressed_values_t;

void receive_pedal_percent_pressed_values(const can_msg_t *message, pedal_percent_pressed_values_t *pedal_percent_pressed_values);

typedef struct {
 float accel1_volts;
 float accel2_volts;
 float brake1_volts;
 float brake2_volts;
} pedal_sensor_voltages_t;

void receive_pedal_sensor_voltages(const can_msg_t *message, pedal_sensor_voltages_t *pedal_sensor_voltages);

typedef struct {
 uint8_t status;
} lightning_board_light_status_t;

void receive_lightning_board_light_status(const can_msg_t *message, lightning_board_light_status_t *lightning_board_light_status);

typedef struct {
 float vcu_temperature;
 float vcu_humidity;
} temperature_sensor_t;

void receive_temperature_sensor(const can_msg_t *message, temperature_sensor_t *temperature_sensor);

typedef struct {
 float imu_accelerometer_x;
 float imu_accelerometer_y;
 float imu_accelerometer_z;
} imu_accelerometer_t;

void receive_imu_accelerometer(const can_msg_t *message, imu_accelerometer_t *imu_accelerometer);

typedef struct {
 float imu_gyro_x;
 float imu_gyro_y;
 float imu_gyro_z;
} imu_gyro_t;

void receive_imu_gyro(const can_msg_t *message, imu_gyro_t *imu_gyro);

typedef struct {
 bool CAN_OUTGOING_FAULT;
 bool CAN_INCOMING_FAULT;
 bool BMS_CAN_MONITOR_FAULT;
 bool LIGHTNING_CAN_MONITOR_FAULT;
 bool SHUTDOWN_FAULT;
 bool ONBOARD_TEMP_FAULT;
 bool IMU_ACCEL_FAULT;
 bool IMU_GYRO_FAULT;
 bool BSPD_PREFAULT;
 bool ONBOARD_BRAKE_OPEN_CIRCUIT_FAULT;
 bool ONBOARD_ACCEL_OPEN_CIRCUIT_FAULT;
 bool ONBOARD_BRAKE_SHORT_CIRCUIT_FAULT;
 bool ONBOARD_ACCEL_SHORT_CIRCUIT_FAULT;
 bool ONBOARD_PEDAL_DIFFERENCE_FAULT;
 bool RTDS_FAULT;
 bool LV_LOW_VOLTAGE_FAULT;
} faults_t;

void receive_faults(const can_msg_t *message, faults_t *faults);

typedef struct {
 uint16_t ADC;
 float Voltage;
} lv_voltage_t;

void receive_lv_voltage(const can_msg_t *message, lv_voltage_t *lv_voltage);

typedef struct {
 uint8_t three_bits;
 float float_value;
 uint8_t five_bits;
 uint16_t sixteen_bits;
 int8_t signed_8_bits;
} vcu_test_message_t;

void receive_vcu_test_message(const can_msg_t *message, vcu_test_message_t *vcu_test_message);

typedef struct {
 uint16_t temp;
} dti_motor_temp_as_reported_by_vcu_t;

void receive_dti_motor_temp_as_reported_by_vcu(const can_msg_t *message, dti_motor_temp_as_reported_by_vcu_t *dti_motor_temp_as_reported_by_vcu);

typedef struct {
 uint16_t temp;
} dti_controller_temp_as_reported_by_vcu_t;

void receive_dti_controller_temp_as_reported_by_vcu(const can_msg_t *message, dti_controller_temp_as_reported_by_vcu_t *dti_controller_temp_as_reported_by_vcu);

typedef struct {
 float temp;
} bms_battbox_temp_as_reported_by_vcu_t;

void receive_bms_battbox_temp_as_reported_by_vcu(const can_msg_t *message, bms_battbox_temp_as_reported_by_vcu_t *bms_battbox_temp_as_reported_by_vcu);

typedef struct {
 bool brake_state;
} brake_state_as_reported_by_vcu_t;

void receive_brake_state_as_reported_by_vcu(const can_msg_t *message, brake_state_as_reported_by_vcu_t *brake_state_as_reported_by_vcu);

typedef struct {
 bool pin_state;
 bool sounding_state;
 bool reverse_state;
 bool error;
} rtds_state_message_t;

void receive_rtds_state_message(const can_msg_t *message, rtds_state_message_t *rtds_state_message);

typedef struct {
 uint16_t raw;
 float voltage;
 float current;
} lfiu_low_current_adc_readings_t;

void receive_lfiu_low_current_adc_readings(const can_msg_t *message, lfiu_low_current_adc_readings_t *lfiu_low_current_adc_readings);

typedef struct {
 uint16_t raw;
 float voltage;
 float current;
} lfiu_high_current_adc_readings_t;

void receive_lfiu_high_current_adc_readings(const can_msg_t *message, lfiu_high_current_adc_readings_t *lfiu_high_current_adc_readings);

typedef struct {
 uint16_t one;
 uint8_t two;
 uint8_t three;
 bool four;
 uint8_t five;
 uint32_t six;
} second_vcu_test_message_t;

void receive_second_vcu_test_message(const can_msg_t *message, second_vcu_test_message_t *second_vcu_test_message);

typedef struct {
 uint8_t fan_pwm_percentage;
} lv_box_fan_pwm_t;

void receive_lv_box_fan_pwm(const can_msg_t *message, lv_box_fan_pwm_t *lv_box_fan_pwm);


void receive_can(const can_msg_t *msg);

#endif