#ifndef _CAN_MSGS_TX_H
#define _CAN_MSGS_TX_H

/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include <stdbool.h>
#include <stdint.h>

/**
* Contents of this message:
* MSB/F/Accel - IMU readings from the board
*/
uint8_t send_front_msb_accel
(float x_force,float y_force,float z_force);

/**
* Contents of this message:
* MSB/F/Gyro - Gyro readings from the board
*/
uint8_t send_front_msb_gyro
(float x_deg,float y_deg,float z_deg);

/**
* Contents of this message:
* MSB/F/Mag - Magnetometer readings from the board
*/
uint8_t send_front_msb_mag
(float x_mag,float y_mag,float z_mag);

/**
* Contents of this message:
* MSB/F/Orientation - MSB orientation as a result of sensor fusion
*/
uint8_t send_front_msb_orientation
(float x_fdeg,float y_fdeg,float z_fdeg);

/**
* Contents of this message:
* MSB/F/Pressure - Pressure Sensor readings
*/
uint8_t send_front_msb_pressure_sensor
(float pressure,float temperature);

/**
* Contents of this message:
* MSB/F/FR_RPM - RPM value of front right wheel
* MSB/F/FL_RPM - RPM value of front left wheel
*/
uint8_t send_front_temperature_sensor
(float temperature,float humidity);

/**
* Contents of this message:
* MSB/F/Strain1 - Strain 1 and 2 readings
*/
uint8_t send_front_msb_strain_one_and_two
(uint32_t strain1,uint32_t strain2);

/**
* Contents of this message:
* MSB/F/Strain2 - Strain 3 and 4 readings
*/
uint8_t send_front_msb_strain_three_and_four
(uint32_t strain3,uint32_t strain4);

/**
* Contents of this message:
* MSB/F/Shock - Shock Pot readings
*/
uint8_t send_front_shockpot
(uint32_t shock1,uint32_t shock2);

/**
* Contents of this message:
* MSB/F/Cells - Load Cell readings
*/
uint8_t send_front_msb_load_cells
(uint32_t cell1,uint32_t cell2);

/**
* Contents of this message:
* MSB/F/FR_RPM - RPM value of front right wheel
* MSB/F/FL_RPM - RPM value of front left wheel
*/
uint8_t send_front_wheel_rpm
(uint16_t Front Right,uint16_t Front Left);

/**
* Contents of this message:
* MSB/F/Angle - Wheel Angle readings
*/
uint8_t send_front_msb_wheel_angle
(uint32_t angle1);

/**
* Contents of this message:
* MSB/B/Accel - IMU readings from the board
*/
uint8_t send_back_msb_accel
(float x_force,float y_force,float z_force);

/**
* Contents of this message:
* MSB/B/Gyro - Gyro readings from the board
*/
uint8_t send_back_msb_gyro
(float x_deg,float y_deg,float z_deg);

/**
* Contents of this message:
* MSB/B/Mag - Magnetometer readings from the board
*/
uint8_t send_back_msb_mag
(float x_mag,float y_mag,float z_mag);

/**
* Contents of this message:
* MSB/B/Orientation - MSB orientation as a result of sensor fusion
*/
uint8_t send_back_msb_orientation
(float x_fdeg,float y_fdeg,float z_fdeg);

/**
* Contents of this message:
* MSB/F/Pressure - Pressure Sensor readings
*/
uint8_t send_back_msb_pressure_sensor
(float pressure,float temperature);

/**
* Contents of this message:
* MSB/F/FR_RPM - RPM value of front right wheel
* MSB/F/FL_RPM - RPM value of front left wheel
*/
uint8_t send_back_temperature_sensor
(float temperature,float humidity);

/**
* Contents of this message:
* MSB/B/Strain1 - Strain 1 and 2 readings
*/
uint8_t send_back_msb_strain_one_and_two
(uint32_t strain1,uint32_t strain2);

/**
* Contents of this message:
* MSB/B/Strain2 - Strain 3 and 4 readings
*/
uint8_t send_back_msb_strain_three_and_four
(uint32_t strain3,uint32_t strain4);

/**
* Contents of this message:
* MSB/B/Shock - Shock Pot readings
*/
uint8_t send_back_shockpot
(uint32_t shock1,uint32_t shock2);

/**
* Contents of this message:
* MSB/B/Cells - Load Cell readings
*/
uint8_t send_back_msb_load_cells
(uint32_t cell1,uint32_t cell2);

/**
* Contents of this message:
* MSB/F/RR_RPM - RPM value of rear right wheel
* MSB/F/RL_RPM - RPM value of rear left wheel
*/
uint8_t send_rear_wheel_rpm
(uint16_t Rear Right,uint16_t Rear Left);

/**
* Contents of this message:
* MSB/B/Thermo - Thermocouple readings
*/
uint8_t send_back_msb_thermocouple
(uint32_t thermo1);

/**
* Contents of this message:
* MSB/B/TOF - Time of flight readings
*/
uint8_t send_back_msb_tof
(uint16_t quadrant1,uint16_t quadrant2,uint16_t quadrant3,uint16_t quadrant4);
#endif